#Sources 
:sources: 
  Contact: 
    :poll_interval: 300
  Opportunity: 
    :poll_interval: 300
  Account: 
    :poll_interval: 300
  Lead: 
    :poll_interval: 300
 
:test: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
:production: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
:development: 
  :licensefile: settings/license.key
  :syncserver: http://localhost:9292/api/application/
  :redis: localhost:6379
